// Generated by MoonBindgen.
#include <moonbit.h>
#include <stdint.h>
#include <string.h>
#include "fixture.h"

MOONBIT_FFI_EXPORT int mbg_bridge_abi_scalar_out(int p0, int32_t *mbg_status) {
  int mbg_value = 0;
  mbg_status[0] = abi_scalar_out(p0, &mbg_value);
  return mbg_value;
}

MOONBIT_FFI_EXPORT abi_handle* mbg_bridge_abi_handle_out(int p0, int32_t *mbg_status) {
  abi_handle* mbg_value = 0;
  mbg_status[0] = abi_handle_out(p0, &mbg_value);
  return mbg_value;
}

MOONBIT_FFI_EXPORT moonbit_bytes_t mbg_bridge_abi_borrowed_text(int p0, int32_t *mbg_absent) {
  const char *mbg_text = abi_borrowed_text(p0);
  if (mbg_text == NULL) {
    mbg_absent[0] = 1;
    return moonbit_make_bytes(0, 0);
  }
  size_t mbg_size = strlen(mbg_text);
  if (mbg_size > INT32_MAX) {
    mbg_absent[0] = 2;
    return moonbit_make_bytes(0, 0);
  }
  mbg_absent[0] = 0;
  moonbit_bytes_t mbg_bytes = moonbit_make_bytes((int32_t)mbg_size, 0);
  memcpy(mbg_bytes, mbg_text, mbg_size);
  return mbg_bytes;
}

MOONBIT_FFI_EXPORT moonbit_bytes_t mbg_bridge_abi_owned_text(int p0, int32_t *mbg_absent) {
  char *mbg_text = abi_owned_text(p0);
  if (mbg_text == NULL) {
    mbg_absent[0] = 1;
    return moonbit_make_bytes(0, 0);
  }
  size_t mbg_size = strlen(mbg_text);
  if (mbg_size > INT32_MAX) {
    abi_free_text(mbg_text);
    mbg_absent[0] = 2;
    return moonbit_make_bytes(0, 0);
  }
  mbg_absent[0] = 0;
  moonbit_bytes_t mbg_bytes = moonbit_make_bytes((int32_t)mbg_size, 0);
  memcpy(mbg_bytes, mbg_text, mbg_size);
  abi_free_text(mbg_text);
  return mbg_bytes;
}
