// Generated by MoonBindgen.
#include <moonbit.h>
#include <stdint.h>
#include <string.h>
#include <limits.h>
#include <stddef.h>
#include "fixture.h"

typedef struct {
  int32_t error;
  point value;
} mbg_value_point_make_result;
static void mbg_value_point_make_finalize(void *raw) { (void)raw; }
MOONBIT_FFI_EXPORT mbg_value_point_make_result *mbg_value_point_make(int p0, int64_t p1, double p2, int32_t p3) {
  typedef char mbg_check_return_x[(sizeof(( (point *)0)->x) == sizeof(int32_t)) ? 1 : -1];
  typedef char mbg_check_return_z[(sizeof(( (point *)0)->z) == sizeof(double)) ? 1 : -1];
  mbg_value_point_make_result *raw = (mbg_value_point_make_result *)moonbit_make_external_object(mbg_value_point_make_finalize, sizeof(mbg_value_point_make_result));
  memset(raw, 0, sizeof(*raw));
  if (p1 < LONG_MIN || p1 > LONG_MAX) { raw->error = 1; return raw; }

  raw->value = point_make(p0, (long)p1, p2, (_Bool)p3);
  return raw;
}
MOONBIT_FFI_EXPORT int32_t mbg_value_point_make_error(mbg_value_point_make_result *raw) { return raw->error; }
MOONBIT_FFI_EXPORT int32_t mbg_value_point_make_x(mbg_value_point_make_result *raw) { return (int32_t)raw->value.x; }
MOONBIT_FFI_EXPORT int64_t mbg_value_point_make_y(mbg_value_point_make_result *raw) { return (int64_t)raw->value.y; }
MOONBIT_FFI_EXPORT double mbg_value_point_make_z(mbg_value_point_make_result *raw) { return (double)raw->value.z; }
MOONBIT_FFI_EXPORT int32_t mbg_value_point_make_valid(mbg_value_point_make_result *raw) { return (int32_t)raw->value.valid; }

typedef struct {
  int32_t error;
  point value;
} mbg_value_point_add_result;
static void mbg_value_point_add_finalize(void *raw) { (void)raw; }
MOONBIT_FFI_EXPORT mbg_value_point_add_result *mbg_value_point_add(int32_t p0_x, int64_t p0_y, double p0_z, int32_t p0_valid, int32_t p1_x, int64_t p1_y, double p1_z, int32_t p1_valid) {
  typedef char mbg_check_0_x[(sizeof(( (point *)0)->x) == sizeof(int32_t)) ? 1 : -1];
  typedef char mbg_check_0_z[(sizeof(( (point *)0)->z) == sizeof(double)) ? 1 : -1];
  typedef char mbg_check_1_x[(sizeof(( (point *)0)->x) == sizeof(int32_t)) ? 1 : -1];
  typedef char mbg_check_1_z[(sizeof(( (point *)0)->z) == sizeof(double)) ? 1 : -1];
  typedef char mbg_check_return_x[(sizeof(( (point *)0)->x) == sizeof(int32_t)) ? 1 : -1];
  typedef char mbg_check_return_z[(sizeof(( (point *)0)->z) == sizeof(double)) ? 1 : -1];
  mbg_value_point_add_result *raw = (mbg_value_point_add_result *)moonbit_make_external_object(mbg_value_point_add_finalize, sizeof(mbg_value_point_add_result));
  memset(raw, 0, sizeof(*raw));
  if (p0_y < LONG_MIN || p0_y > LONG_MAX || p1_y < LONG_MIN || p1_y > LONG_MAX) { raw->error = 1; return raw; }
  point value0;
  memset(&value0, 0, sizeof(value0));
  value0.x = (int)p0_x;
  value0.y = (long)p0_y;
  value0.z = (double)p0_z;
  value0.valid = (_Bool)p0_valid;
  point value1;
  memset(&value1, 0, sizeof(value1));
  value1.x = (int)p1_x;
  value1.y = (long)p1_y;
  value1.z = (double)p1_z;
  value1.valid = (_Bool)p1_valid;
  raw->value = point_add(value0, value1);
  return raw;
}
MOONBIT_FFI_EXPORT int32_t mbg_value_point_add_error(mbg_value_point_add_result *raw) { return raw->error; }
MOONBIT_FFI_EXPORT int32_t mbg_value_point_add_x(mbg_value_point_add_result *raw) { return (int32_t)raw->value.x; }
MOONBIT_FFI_EXPORT int64_t mbg_value_point_add_y(mbg_value_point_add_result *raw) { return (int64_t)raw->value.y; }
MOONBIT_FFI_EXPORT double mbg_value_point_add_z(mbg_value_point_add_result *raw) { return (double)raw->value.z; }
MOONBIT_FFI_EXPORT int32_t mbg_value_point_add_valid(mbg_value_point_add_result *raw) { return (int32_t)raw->value.valid; }

typedef struct {
  int32_t error;
  int value;
} mbg_value_point_score_result;
static void mbg_value_point_score_finalize(void *raw) { (void)raw; }
MOONBIT_FFI_EXPORT mbg_value_point_score_result *mbg_value_point_score(int32_t p0_x, int64_t p0_y, double p0_z, int32_t p0_valid) {
  typedef char mbg_check_0_x[(sizeof(( (point *)0)->x) == sizeof(int32_t)) ? 1 : -1];
  typedef char mbg_check_0_z[(sizeof(( (point *)0)->z) == sizeof(double)) ? 1 : -1];
  mbg_value_point_score_result *raw = (mbg_value_point_score_result *)moonbit_make_external_object(mbg_value_point_score_finalize, sizeof(mbg_value_point_score_result));
  memset(raw, 0, sizeof(*raw));
  if (p0_y < LONG_MIN || p0_y > LONG_MAX) { raw->error = 1; return raw; }
  point value0;
  memset(&value0, 0, sizeof(value0));
  value0.x = (int)p0_x;
  value0.y = (long)p0_y;
  value0.z = (double)p0_z;
  value0.valid = (_Bool)p0_valid;
  raw->value = point_score(value0);
  return raw;
}
MOONBIT_FFI_EXPORT int32_t mbg_value_point_score_error(mbg_value_point_score_result *raw) { return raw->error; }
MOONBIT_FFI_EXPORT int mbg_value_point_score_value(mbg_value_point_score_result *raw) { return (int)raw->value; }

typedef struct {
  int32_t error;
  point_alias value;
} mbg_value_point_passthrough_result;
static void mbg_value_point_passthrough_finalize(void *raw) { (void)raw; }
MOONBIT_FFI_EXPORT mbg_value_point_passthrough_result *mbg_value_point_passthrough(int32_t p0_x, int64_t p0_y, double p0_z, int32_t p0_valid) {
  typedef char mbg_check_0_x[(sizeof(( (point_alias *)0)->x) == sizeof(int32_t)) ? 1 : -1];
  typedef char mbg_check_0_z[(sizeof(( (point_alias *)0)->z) == sizeof(double)) ? 1 : -1];
  typedef char mbg_check_return_x[(sizeof(( (point_alias *)0)->x) == sizeof(int32_t)) ? 1 : -1];
  typedef char mbg_check_return_z[(sizeof(( (point_alias *)0)->z) == sizeof(double)) ? 1 : -1];
  mbg_value_point_passthrough_result *raw = (mbg_value_point_passthrough_result *)moonbit_make_external_object(mbg_value_point_passthrough_finalize, sizeof(mbg_value_point_passthrough_result));
  memset(raw, 0, sizeof(*raw));
  if (p0_y < LONG_MIN || p0_y > LONG_MAX) { raw->error = 1; return raw; }
  point_alias value0;
  memset(&value0, 0, sizeof(value0));
  value0.x = (int)p0_x;
  value0.y = (long)p0_y;
  value0.z = (double)p0_z;
  value0.valid = (_Bool)p0_valid;
  raw->value = point_passthrough(value0);
  return raw;
}
MOONBIT_FFI_EXPORT int32_t mbg_value_point_passthrough_error(mbg_value_point_passthrough_result *raw) { return raw->error; }
MOONBIT_FFI_EXPORT int32_t mbg_value_point_passthrough_x(mbg_value_point_passthrough_result *raw) { return (int32_t)raw->value.x; }
MOONBIT_FFI_EXPORT int64_t mbg_value_point_passthrough_y(mbg_value_point_passthrough_result *raw) { return (int64_t)raw->value.y; }
MOONBIT_FFI_EXPORT double mbg_value_point_passthrough_z(mbg_value_point_passthrough_result *raw) { return (double)raw->value.z; }
MOONBIT_FFI_EXPORT int32_t mbg_value_point_passthrough_valid(mbg_value_point_passthrough_result *raw) { return (int32_t)raw->value.valid; }
