// Generated by MoonBindgen.
#include <moonbit.h>
#include <stdint.h>
#include <string.h>
#include <limits.h>
#include <stddef.h>
#include "fixture.h"

typedef struct {
  void (*invoke)(void*, int32_t);
  void *closure;
  int32_t active;
} mbg_registration_register_listener;
static void mbg_callback_register_listener_close_state(mbg_registration_register_listener *state) {
  if (!state->active) return;
  state->active = 0;
  unregister_listener(state);
  void *closure = state->closure;
  state->closure = NULL;
  moonbit_decref(closure);
}
static void mbg_callback_register_listener_finalize(void *raw) {
  mbg_callback_register_listener_close_state((mbg_registration_register_listener *)raw);
}
static void mbg_callback_register_listener_dispatch(void *data, int value) {
  mbg_registration_register_listener *state = (mbg_registration_register_listener *)data;
  if (!state->active) return;
  void *closure = state->closure;
  moonbit_incref(state);
  moonbit_incref(closure);
  state->invoke(closure, (int32_t)value);
  moonbit_decref(closure);
  moonbit_decref(state);
}
MOONBIT_FFI_EXPORT mbg_registration_register_listener *mbg_callback_register_listener(void (*invoke)(void*, int32_t), void *closure) {
  typedef char mbg_check_int[(sizeof(int) == sizeof(int32_t)) ? 1 : -1];
  mbg_registration_register_listener *state = (mbg_registration_register_listener *)moonbit_make_external_object(mbg_callback_register_listener_finalize, sizeof(mbg_registration_register_listener));
  state->invoke = invoke;
  state->closure = closure;
  state->active = 1;
  moonbit_incref(closure);
  register_listener(mbg_callback_register_listener_dispatch, state);
  return state;
}
MOONBIT_FFI_EXPORT int32_t mbg_callback_register_listener_close(mbg_registration_register_listener *state) {
  if (!state->active) return 0;
  mbg_callback_register_listener_close_state(state);
  return 1;
}
MOONBIT_FFI_EXPORT int32_t mbg_callback_register_listener_active(mbg_registration_register_listener *state) { return state->active; }
