// Generated by MoonBindgen.
#include <moonbit.h>
#include <stdint.h>
#include <string.h>
#include "sqlite3.h"

MOONBIT_FFI_EXPORT moonbit_bytes_t mbg_bridge_sqlite3_libversion(int32_t *mbg_absent) {
  const char *mbg_text = sqlite3_libversion();
  if (mbg_text == NULL) {
    mbg_absent[0] = 1;
    return moonbit_make_bytes(0, 0);
  }
  size_t mbg_size = strlen(mbg_text);
  if (mbg_size > INT32_MAX) {
    mbg_absent[0] = 2;
    return moonbit_make_bytes(0, 0);
  }
  mbg_absent[0] = 0;
  moonbit_bytes_t mbg_bytes = moonbit_make_bytes((int32_t)mbg_size, 0);
  memcpy(mbg_bytes, mbg_text, mbg_size);
  return mbg_bytes;
}

MOONBIT_FFI_EXPORT sqlite3* mbg_bridge_sqlite3_open(moonbit_bytes_t p0, int32_t *mbg_status) {
  sqlite3* mbg_value = 0;
  mbg_status[0] = sqlite3_open((const char *)p0, &mbg_value);
  return mbg_value;
}

MOONBIT_FFI_EXPORT sqlite3_stmt* mbg_bridge_sqlite3_prepare_v2(sqlite3 * p0, moonbit_bytes_t p1, int p2, int32_t *mbg_status) {
  sqlite3_stmt* mbg_value = 0;
  mbg_status[0] = sqlite3_prepare_v2(p0, (const char *)p1, p2, &mbg_value, NULL);
  return mbg_value;
}
