// Generated by MoonBindgen.
#include <moonbit.h>
#include <stdint.h>
#include <string.h>
#include <limits.h>
#include <stddef.h>
#include "fixture.h"

MOONBIT_FFI_EXPORT int32_t mbg_bridge_abi_buffer_sum(moonbit_bytes_t p0, int32_t *mbg_error) {
  size_t mbg_len = (size_t)Moonbit_array_length(p0);
  if (mbg_len > INT32_MAX) { mbg_error[0] = 1; return 0; }
  mbg_error[0] = 0;
  return abi_buffer_sum((const void *)p0, (int)mbg_len);
}

MOONBIT_FFI_EXPORT moonbit_bytes_t mbg_bridge_abi_buffer_fill(int32_t p0, int32_t *mbg_error) {
  if (p0 < 0) { mbg_error[0] = 1; return moonbit_make_bytes(0, 0); }
  mbg_error[0] = 0;
  moonbit_bytes_t mbg_bytes = moonbit_make_bytes(p0, 0);
  abi_buffer_fill((int)p0, (void *)mbg_bytes);
  return mbg_bytes;
}

MOONBIT_FFI_EXPORT moonbit_bytes_t mbg_bridge_abi_buffer_view(int p0, int32_t *mbg_absent) {
  int mbg_is_null = abi_buffer_view_null(p0) == ABI_NULL;
  const void *mbg_pointer = abi_buffer_view(p0);
  long long mbg_size = (long long)abi_buffer_view_length(p0);
  if (mbg_is_null) { mbg_absent[0] = 1; return moonbit_make_bytes(0, 0); }
  if (mbg_size < 0 || mbg_size > INT32_MAX || (mbg_pointer == NULL && mbg_size > 0)) {
    mbg_absent[0] = 2; return moonbit_make_bytes(0, 0);
  }
  mbg_absent[0] = 0;
  moonbit_bytes_t mbg_bytes = moonbit_make_bytes((int32_t)mbg_size, 0);
  if (mbg_size > 0) memcpy(mbg_bytes, mbg_pointer, (size_t)mbg_size);
  return mbg_bytes;
}

MOONBIT_FFI_EXPORT int32_t mbg_bridge_abi_short(int32_t p0, int32_t *mbg_error) {
  if (p0 < SHRT_MIN || p0 > SHRT_MAX) { mbg_error[0] = 1; return 0; }
  mbg_error[0] = 0;
  return (int32_t)abi_short((short)p0);
}

MOONBIT_FFI_EXPORT uint32_t mbg_bridge_abi_ushort(uint32_t p0, int32_t *mbg_error) {
  if (p0 > USHRT_MAX) { mbg_error[0] = 1; return 0; }
  mbg_error[0] = 0;
  return (uint32_t)abi_ushort((unsigned short)p0);
}

MOONBIT_FFI_EXPORT int64_t mbg_bridge_abi_long(int64_t p0, int32_t *mbg_error) {
  if (p0 < LONG_MIN || p0 > LONG_MAX) { mbg_error[0] = 1; return 0; }
  mbg_error[0] = 0;
  return (int64_t)abi_long((long)p0);
}

MOONBIT_FFI_EXPORT uint64_t mbg_bridge_abi_size(uint64_t p0, int32_t *mbg_error) {
  if (p0 > SIZE_MAX) { mbg_error[0] = 1; return 0; }
  mbg_error[0] = 0;
  return (uint64_t)abi_size((size_t)p0);
}

MOONBIT_FFI_EXPORT int32_t mbg_bridge_abi_bool(int32_t p0, int32_t *mbg_error) {
  mbg_error[0] = 0;
  return (int32_t)abi_bool((_Bool)p0);
}
