// Generated by MoonBindgen.
#include <moonbit.h>
#include <stdint.h>
#include <string.h>
#include <limits.h>
#include <stddef.h>
#include "fixture.h"

typedef struct {
  int32_t error;
  int32_t status;
  int out1;
  long out2;
  token * out3;
} mbg_bridge_make_pair_result;
static void mbg_bridge_make_pair_finalize(void *raw) { (void)raw; }
MOONBIT_FFI_EXPORT mbg_bridge_make_pair_result *mbg_bridge_make_pair(int p0) {
  mbg_bridge_make_pair_result *mbg_result = (mbg_bridge_make_pair_result *)moonbit_make_external_object(mbg_bridge_make_pair_finalize, sizeof(mbg_bridge_make_pair_result));
  memset(mbg_result, 0, sizeof(*mbg_result));
  mbg_result->status = make_pair(p0, &mbg_result->out1, &mbg_result->out2, &mbg_result->out3);
  return mbg_result;
}
MOONBIT_FFI_EXPORT int32_t mbg_bridge_make_pair_error(mbg_bridge_make_pair_result *raw) { return raw->error; }
MOONBIT_FFI_EXPORT int32_t mbg_bridge_make_pair_status(mbg_bridge_make_pair_result *raw) { return raw->status; }
MOONBIT_FFI_EXPORT int mbg_bridge_make_pair_out1(mbg_bridge_make_pair_result *raw) { return (int)raw->out1; }
MOONBIT_FFI_EXPORT int64_t mbg_bridge_make_pair_out2(mbg_bridge_make_pair_result *raw) { return (int64_t)raw->out2; }
MOONBIT_FFI_EXPORT token * mbg_bridge_make_pair_out3(mbg_bridge_make_pair_result *raw) { return (token *)raw->out3; }

typedef struct {
  token * handle;
  int32_t error;
} mbg_state_token;
static void mbg_resource_token_new_finalize(void *raw) {
  mbg_state_token *state = (mbg_state_token *)raw;
  if (state->handle != NULL) {
    token * handle = state->handle;
    state->handle = NULL;
    token_free(handle);
  }
}
MOONBIT_FFI_EXPORT mbg_state_token *mbg_resource_token_new(int p0) {
  mbg_state_token *state = (mbg_state_token *)moonbit_make_external_object(mbg_resource_token_new_finalize, sizeof(mbg_state_token));
  state->handle = NULL;
  state->error = 0;
  state->handle = token_new(p0);
  return state;
}
MOONBIT_FFI_EXPORT int32_t mbg_resource_token_new_error(mbg_state_token *state) { return state->error; }
MOONBIT_FFI_EXPORT int32_t mbg_resource_token_new_valid(mbg_state_token *state) { return state->handle != NULL; }
MOONBIT_FFI_EXPORT int32_t mbg_resource_token_new_close(mbg_state_token *state) {
  if (state->handle == NULL) return 0;
  token * handle = state->handle;
  state->handle = NULL;
  token_free(handle);
  return 1;
}
MOONBIT_FFI_EXPORT token * mbg_resource_token_new_raw(void *state_raw) { mbg_state_token *state = (mbg_state_token *)state_raw; return state->handle; }
MOONBIT_FFI_EXPORT mbg_state_token *mbg_resource_token_new_retain(mbg_state_token *state) {
  mbg_state_token *copy = (mbg_state_token *)moonbit_make_external_object(mbg_resource_token_new_finalize, sizeof(mbg_state_token));
  copy->handle = NULL;
  copy->error = 0;
  if (state->handle != NULL) {
    token_retain(state->handle);
    copy->handle = state->handle;
  }
  return copy;
}

extern token * mbg_resource_token_new_raw(void *state_raw);
MOONBIT_FFI_EXPORT token * mbg_view_token_borrow(void *owner, int32_t *absent) {
  token * handle = mbg_resource_token_new_raw(owner);
  if (handle == NULL) { absent[0] = 2; return NULL; }
  token * view = token_borrow(handle);
  absent[0] = view == NULL ? 1 : 0;
  return view;
}
